# Generated by Django 5.0.6 on 2026-07-19 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='show_on_home',
            field=models.BooleanField(default=False, verbose_name='Show on Home Page'),
        ),
    ]
