# Generated by Django 5.0.6 on 2026-07-19 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_galleryimage_show_on_home'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryimage',
            name='show_on_home',
        ),
        migrations.AddField(
            model_name='gallery',
            name='show_on_home',
            field=models.BooleanField(default=False, verbose_name='Show on Home Page'),
        ),
    ]
