# Generated by Django 5.0.6 on 2026-07-26 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('shop_name', models.CharField(max_length=150)),
                ('mobile', models.CharField(max_length=15, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('browser', models.CharField(blank=True, max_length=100)),
                ('device', models.CharField(blank=True, max_length=100)),
                ('operating_system', models.CharField(blank=True, max_length=100)),
                ('user_agent', models.TextField(blank=True)),
                ('visit_count', models.PositiveIntegerField(default=1)),
                ('last_visit', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Visitor Lead',
                'verbose_name_plural': 'Visitor Leads',
                'ordering': ['-last_visit'],
            },
        ),
    ]
