# Generated by Django 5.0.6 on 2026-07-22 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, help_text='e.g. Ahmedabad, Gujarat', max_length=100, null=True)),
                ('image', models.ImageField(upload_to='testimonials/')),
                ('review_rate', models.PositiveSmallIntegerField(default=5)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sf_testimonial',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
