# Generated by Django 5.0.6 on 2026-07-23 05:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testinomial', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimonial',
            options={'ordering': ['sort_order', 'id'], 'verbose_name': 'Testimonial', 'verbose_name_plural': 'Testimonials'},
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='description',
            field=models.TextField(verbose_name='Review Text'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='testimonials/'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this review is visible on the site.'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Customer Name'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='review_rate',
            field=models.DecimalField(decimal_places=1, default=5.0, help_text='Enter rating between 1.0 and 5.0 (e.g. 3.5)', max_digits=2, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, help_text='Lower number appears first'),
        ),
    ]
