# Generated by Django 5.2.16 on 2026-07-18 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_seed_boy_girl_categories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['section', 'sort_order', 'name'], 'verbose_name_plural': 'categories'},
        ),
        migrations.AddField(
            model_name='category',
            name='section',
            field=models.CharField(choices=[('women', 'Women'), ('kids', 'Kids')], default='women', help_text='Women products show on /women/, Kids products show on /kids/ only.', max_length=20),
        ),
    ]
